#Description: Fatfs MMC layer; user_visible: True
include_guard(GLOBAL)
message("middleware_fatfs_mmc component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/source/fsl_mmc_disk/fsl_mmc_disk.c
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/source/fsl_mmc_disk
)

#OR Logic component
if(${MCUX_DEVICE} STREQUAL "LPC54607")
    include(middleware_fatfs_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S016")
    include(middleware_fatfs_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54606")
    include(middleware_fatfs_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54616")
    include(middleware_fatfs_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54016")
    include(middleware_fatfs_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54018")
    include(middleware_fatfs_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54628")
    include(middleware_fatfs_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54605")
    include(middleware_fatfs_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54618")
    include(middleware_fatfs_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT555S_cm33")
    include(middleware_fatfs_MIMXRT595S_cm33)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54018M")
    include(middleware_fatfs_LPC54S018M)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018")
    include(middleware_fatfs_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018M")
    include(middleware_fatfs_LPC54S018M)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S005")
    include(middleware_fatfs_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54005")
    include(middleware_fatfs_LPC54S018)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT533S_cm33")
    include(middleware_fatfs_MIMXRT595S_cm33)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54608")
    include(middleware_fatfs_LPC54628)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT595S_cm33")
    include(middleware_fatfs_MIMXRT595S_cm33)
endif()

include(middleware_sdmmc_mmc)
include(middleware_fatfs)